name: Test and Build

on:
  workflow_run:
    workflows: ["Main"]
    branches: [develop, master]
    types: [completed]

jobs:
  test_and_build:
    name: Test and Build
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Cache
      uses: actions/cache@v2
      with:
        path: Library
        key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-

    - name: Test
      uses: game-ci/unity-test-runner@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_VERSION_2020_LICENSE }}
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_VERSION_2020_LICENSE }}
      with:
        targetPlatform: WebGL

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build
